Feature/kontakt oss form
magnusouren/cribadvisor pull request #19
Opened 2021-11-01 13:25 UTC by taleeikenes

2021-11-01 14:18 UTC, isaksolheim commented on styles/kontakt-oss.css
> +#Besøk_oss {
burde være små bokstaver og ingen æøå

2021-11-01 14:23 UTC, isaksolheim commented on kontakt-oss.html
> +      <button type="submit" id=button>Send</button>
Kan du legge til css sånn at musepeker skifter til `pointer` modus når man holder musa over?

2021-11-01 14:24 UTC, isaksolheim commented on kontakt-oss.html
> +
Kommentarene kan fjernes så ser fila litt ryddigere ut :D

2021-11-01 14:29 UTC, isaksolheim requested changes
Mente å klikke request changes :P

2021-11-08 11:06 UTC, merged

2021-11-08 11:16 UTC, taleeikenes commented on styles/kontakt-oss.css
> +#Besøk_oss {
jeg forstår ikke denne kommentaren