Feature/hybel popup
magnusouren/cribadvisor pull request #35
Opened 2021-11-08 13:42 UTC by magnusouren

Lagt til id på kappene "kontakt" og "vurdering i `hybel.js`

Laget et script (`hybelPopUp.js`) som lager en stor div som dekker hele skjermen med "grønn" farge. Og en liten hvit div som senere kan vise innhold. 

> Her setter jeg høyden til div-elementet ved hjelp av å finne høyden til innholdet på siden i js, mulig dette kan gjøres enklere ved hjelp av css, men dette klarte jeg ikke å finne ut av

Lagt til stil på disse div-elementene i `hybel.css`

2021-11-09 09:12 UTC, isaksolheim approved these changes
Veldig bra 🤩 eneste småting er at css bruker som vanlig ikke camelCase, men bindestrek-i-navn. Tipper vi ikke får noe trekk for det tho :P

2021-11-09 09:32 UTC, magnusouren commented
Gjør en del større justeringer på koden, gir en lyd når jeg er fornøyd :))

2021-11-09 11:26 UTC, isaksolheim requested changes

2021-11-09 11:26 UTC, isaksolheim commented on script/hybelPopUp.js
> +  });
Med tanke på at `button` parameterne er strings så ville jeg kalt den for noe annet enn `button`, f.eks. `buttonName`. Ble litt forvirret av hva det var foe noe

2021-11-09 11:26 UTC, isaksolheim commented on script/hybelPopUp.js
> +  if (button == 'contact') {
Burde bruke `button === 'contact'`, da får man med type safety i tillegg :D

2021-11-09 11:26 UTC, isaksolheim commented on script/hybelPopUp.js
> +  } else if ((button = 'rating')) {
samme som over, `button = 'rating'` er feil

2021-11-09 12:23 UTC, magnusouren commented
Så nå at det mangler kontaktinfo i data.js, greit å adde dette i denne branchen eller skal vi ha ny branch for det?

2021-11-09 12:39 UTC, isaksolheim commented
Bare å adde i denne

2021-11-09 17:04 UTC, magnusouren commented
Har nå gjort det jeg rekker på denne idag, og er opptatt i morgen. Dette funker som det skal, men noe kan sikkert med fordel skrives om på en bedre måte. Om du vil se over @isaksolheim, så er det bare merge når du er happy. Ellers er jeg tilgjengelig på melding om det skulle være noe.

2021-11-10 09:40 UTC, isaksolheim approved these changes

2021-11-10 09:40 UTC, merged